import { DenoDeps, Fs, type t } from './common.ts';

const PI_CODING_AGENT_IMPORT_BASE = 'npm:@mariozechner/pi-coding-agent' as const;

/**
 * AUTO-GENERATED by `code/sys.driver/driver-pi/-scripts/task.prep.ts`.
 * Keeps the fallback deterministic when no local `deps.yaml` is present.
 */
export const PI_CODING_AGENT_IMPORT = 'npm:@mariozechner/pi-coding-agent@0.71.0' as const;

/**
 * Resolve the Pi package spec from an explicit override or canonical deps file.
 */
export async function resolvePkg(input: {
  readonly cwd: t.StringDir;
  readonly pkg?: t.StringModuleSpecifier;
}) {
  if (input.pkg) return input.pkg;
  const depsPath = await findDepsPath(input.cwd);
  if (!depsPath) return PI_CODING_AGENT_IMPORT;

  const res = await DenoDeps.from(depsPath);
  if (res.error) throw res.error;

  return DenoDeps.findImport(res.data?.deps, PI_CODING_AGENT_IMPORT_BASE) ?? PI_CODING_AGENT_IMPORT;
}

/**
 * Helpers:
 */
async function findDepsPath(cwd: t.StringDir) {
  if (!(await Fs.exists(cwd))) return undefined;
  let found: t.StringPath | undefined;
  await Fs.walkUp(cwd, async ({ dir, stop }) => {
    const path = Fs.join(dir, 'deps.yaml');
    if (!(await Fs.exists(path))) return;
    found = path;
    stop();
  });
  return found;
}
