import { Fs, Str, c } from './common.ts';

const TARGET = './code/sys/monorepo/src/m.ci/u.deno.ts';

export async function main() {
  const next = text();
  await Fs.write(TARGET, next, { force: true });

  console.info(
    c.brightCyan('Updated file:'),
    c.gray(Fs.trimCwd(TARGET)),
    c.white(`(Deno ${Deno.version.deno})`),
  );
}

function text(version = Deno.version.deno) {
  return Str.dedent(`
    /**
     * Generated by \`deno task prep:ci:deno\`.
     */
    export const CI_DENO_VERSION = 'v${version}' as const;

  `);
}
