// AUTO-GENERATED by `deno task bind:gui:evidence:local`.
// DO NOT EDIT MANUALLY.
// Checked in so `start:gui` can authenticate one frozen local-rehearsal build.
// This is not published release evidence.

export const START_GUI_RELEASE_EVIDENCE = Object.freeze({
  kind: 'release' as const,
  manifestUrl: 'http://localhost:8080/dist.json',
  integrity: 'sha256-187273216d52bfaca653fa21700f805c6ea135fa580105f6550ec3ca785ab18b',
  expectedPkg: Object.freeze({
    name: '@sys/driver-pi',
    version: '0.0.138',
  }),
});
