name: ci

on:
  push:
    branches: ['main']
    paths-ignore:
      - 'README.md'
      - '-docs/**'
      - '-agent/**'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '-docs/**'
      - '-agent/**'

jobs:
  deno:
    name: Deno Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Deno 2.x
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: System tools
        run: deno run -A jsr:@sys/tools -h --no-interactive

      - name: Deno check
        run: deno task check

      - name: Deno test
        run: deno task test
