import { Fs } from '@sys/fs';

const ROOT = import.meta.dirname ? Fs.resolve(import.meta.dirname, '..') : Fs.cwd();
const SVG_FILE = Fs.join(ROOT, 'src/ui/ui.Logo.Canvas/canvas.mini.svg');
const TS_FILE = Fs.join(ROOT, 'src/ui/ui.Logo.Canvas/canvas.mini.ts');

/**
 * Generate the publish-safe TS surface from the authored SVG file.
 * Why: JSR consumers should import TS, not rely on package-internal SVG asset resolution.
 */
export async function main() {
  const svg = (await Fs.readText(SVG_FILE)).data ?? '';
  if (!svg.trim()) throw new Error(`SVG source is empty: ${SVG_FILE}`);

  const escaped = svg
    .replaceAll('\\', '\\\\')
    .replaceAll('`', '\\`')
    .replaceAll('${', '\\${');

  const output = [
    '/**',
    ' * AUTO-GENERATED by `./-scripts/-gen.logo-canvas-svg.ts`.',
    ' * Source of truth: `./canvas.mini.svg`.',
    ' * Why: keep the authored SVG as a file while publishing a TS-only runtime surface.',
    ' */',
    '',
    'export const CANVAS_MINI_SVG_MARKUP = `',
    escaped,
    '`;',
    '',
  ].join('\n');

  const write = await Fs.write(TS_FILE, output, { force: true });
  if (write.error) throw write.error;
  console.info(`Generated ${TS_FILE}`);
}

if (import.meta.main) await main();
