import { type t, DenoFile, Fs, Is, Process } from './common.ts';

/**
 * AUTO-GENERATED by `code/sys.tools/-scripts/-prep.ts`.
 * Keeps the external delegation target deterministic for published tools.
 */
const TMPL_JSR_SPECIFIER = 'jsr:@sys/tmpl@0.0.354';

/**
 * Main entry.
 *
 * Delegates all argv/cwd handling to `@sys/tmpl`.
 */
export const cli: t.TmplToolsLib['cli'] = async (cwd, argv) => {
  cwd = cwd ?? Fs.cwd('terminal');
  argv = argv ?? [];
  const res = await run(cwd, argv);
  if (!res.success && Is.num(res.code)) Deno.exitCode = res.code;
};

/**
 * Execute delegated CLI process with inherited stdio.
 */
async function run(cwd: t.StringDir, argv: string[]) {
  const specifier = await resolveSpecifier(cwd);
  return await Process.inherit({
    cwd,
    args: ['run', '-A', specifier, ...argv],
  });
}

type WorkspaceInfo = {
  readonly exists: boolean;
  readonly dir: t.StringDir;
  readonly file: t.StringPath;
  readonly children: readonly {
    readonly pkg: { readonly name: string };
    readonly path: { readonly dir: t.StringDir };
  }[];
};

async function resolveSpecifier(cwd: t.StringDir): Promise<string> {
  const nearest = await DenoFile.nearest(cwd, (e) => Array.isArray(e.file.workspace));
  if (!nearest?.is.workspace) return TMPL_JSR_SPECIFIER;

  const ws = await DenoFile.workspace(nearest.path, { walkup: false });
  if (!isSystemRepo(ws)) return TMPL_JSR_SPECIFIER;
  return '@sys/tmpl';
}

function isSystemRepo(ws: WorkspaceInfo): boolean {
  if (!ws.exists) return false;
  if (Fs.basename(ws.dir) !== 'sys') return false;
  if (!['deno.json', 'deno.jsonc'].includes(Fs.basename(ws.file))) return false;

  const names = new Set(ws.children.map((child) => child.pkg.name));
  if (!names.has('@sys/tools') || !names.has('@sys/tmpl')) return false;

  const dirs = new Set(ws.children.map((child) => child.path.dir));
  if (!dirs.has('code/sys.tools') || !dirs.has('code/-tmpl')) return false;

  return true;
}
