import { Fs, Is, Process, type t } from '../common.ts';
import { resolvePassThroughContext } from '../u.passThrough/u.context.ts';
import type { PassThroughTarget } from '../u.passThrough/t.ts';

/**
 * AUTO-GENERATED by `code/sys.tools/-scripts/task.prep.ts`.
 * Keeps the external delegation target deterministic for published tools.
 */
const TMPL_JSR_SPECIFIER = 'jsr:@sys/tmpl@0.0.365';
const TARGET = {
  localSpecifier: '@sys/tmpl',
  publishedSpecifier: TMPL_JSR_SPECIFIER,
  repo: {
    rootDirname: 'sys',
    configFilenames: ['deno.json', 'deno.jsonc'],
    requiredPackages: ['@sys/tools', '@sys/tmpl'],
    requiredDirs: ['code/sys.tools', 'code/-tmpl'],
  },
} satisfies PassThroughTarget;

/**
 * Main entry.
 *
 * Delegates all argv/cwd handling to `@sys/tmpl`.
 */
export const cli: t.TmplToolsLib['cli'] = async (cwd, argv) => {
  cwd = cwd ?? Fs.cwd('terminal');
  argv = argv ?? [];
  const res = await run(cwd, argv);
  if (!res.success && Is.num(res.code)) Deno.exitCode = res.code;
};

async function run(cwd: t.StringDir, argv: string[]) {
  const ctx = await resolvePassThroughContext({ cwd, target: TARGET });
  return await Process.inherit({
    cwd,
    args: ['run', '-A', ctx.specifier, ...argv],
  });
}

if (import.meta.main) {
  await cli(Fs.cwd('terminal'), Deno.args);
}
