import { Fs, Is, Process, type t } from '../common.ts';
import { resolvePassThroughContext } from '../u.passThrough/u.context.ts';
import type { PassThroughTarget } from '../u.passThrough/t.ts';

/**
 * AUTO-GENERATED by `code/sys.tools/-scripts/task.prep.ts`.
 * Keeps the external delegation target deterministic for published tools.
 */
const TMPL_JSR_SPECIFIER = 'jsr:@sys/tmpl@0.0.480';
const TARGET = {
  localSpecifier: '@sys/tmpl',
  publishedSpecifier: TMPL_JSR_SPECIFIER,
  repo: {
    rootDirname: 'sys',
    configFilenames: ['deno.json', 'deno.jsonc'],
    requiredPackages: ['@sys/tools', '@sys/tmpl'],
    requiredDirs: ['code/sys.tools', 'code/-tmpl'],
  },
} satisfies PassThroughTarget;

export type TmplCliDeps = {
  readonly inherit: typeof Process.inherit;
  readonly resolveContext?: typeof resolvePassThroughContext;
};

const DEFAULT_DEPS: TmplCliDeps = Object.freeze({
  inherit: Process.inherit,
  resolveContext: resolvePassThroughContext,
});

/** Internal template pass-through runner with explicit process effects. */
export async function cliTmplWith(
  cwd: t.StringDir | undefined,
  argv: string[] | undefined,
  deps: TmplCliDeps = DEFAULT_DEPS,
): Promise<void> {
  cwd = cwd ?? Fs.cwd('terminal');
  argv = argv ?? [];
  const resolveContext = deps.resolveContext ?? resolvePassThroughContext;
  const ctx = await resolveContext({ cwd, target: TARGET });
  const res = await deps.inherit({
    cwd,
    args: ['run', '-ERW', ctx.specifier, ...argv],
  });
  if (!res.success && Is.num(res.code)) Deno.exitCode = res.code;
}
