/**
 * @module
 * Pass-through CLI entry for launching `@sys/driver-pi/cli`
 * via the `@sys/tools/pi` published surface.
 */
import { Fs, Is, Process, type t } from '../common.ts';
import { resolvePassThroughContext } from '../u.passThrough/u.context.ts';
import type { PassThroughTarget } from '../u.passThrough/t.ts';
import { runWithRootUpgradeAdvisory } from '../u.root/u.upgradeAdvisory.ts';

/**
 * AUTO-GENERATED by `code/sys.tools/-scripts/task.prep.ts`.
 * Keeps the published fallback deterministic for `@sys/tools/pi`.
 */
const DRIVER_PI_CLI_JSR_SPECIFIER = 'jsr:@sys/driver-pi@0.0.114/cli';
const TARGET = {
  localSpecifier: '@sys/driver-pi/cli',
  publishedSpecifier: DRIVER_PI_CLI_JSR_SPECIFIER,
  repo: {
    rootDirname: 'sys',
    configFilenames: ['deno.json', 'deno.jsonc'],
    requiredPackages: ['@sys/tools', '@sys/driver-pi'],
    requiredDirs: ['code/sys.tools', 'code/sys.driver/driver-pi'],
  },
} satisfies PassThroughTarget;

/**
 * CLI pass-through for the published Pi launcher surface.
 *
 * Delegates all argv/cwd handling to the Pi profile launcher.
 */
export const cli: t.PiToolsLib['cli'] = async (cwd, argv) => {
  cwd = cwd ?? Fs.cwd('process');
  argv = argv ?? [];
  const res = await run(cwd, argv);
  if (!res.success && Is.num(res.code)) Deno.exitCode = res.code;
};

async function run(cwd: t.StringDir, argv: string[]) {
  const ctx = await resolvePassThroughContext({ cwd, target: TARGET });
  return await Process.inherit({
    cmd: 'deno',
    cwd,
    env: {
      INIT_CWD: cwd,
      PI_CLI_PROFILES_HELP_TOOL: 'deno run -A jsr:@sys/tools pi',
    },
    args: ['run', '-A', ctx.specifier, ...argv],
  });
}

if (import.meta.main) {
  await runWithRootUpgradeAdvisory(() => cli(Fs.cwd('process'), Deno.args));
}
