import { Fs, Is, Process, type t } from '../common.ts';
import { resolvePassThroughContext } from '../u.passThrough/u.context.ts';
import type { PassThroughTarget } from '../u.passThrough/t.ts';

/**
 * AUTO-GENERATED by `code/sys.tools/-scripts/task.prep.ts`.
 * Keeps the published fallback deterministic for `@sys/tools/pi`.
 */
const DRIVER_PI_CLI_JSR_SPECIFIER = 'jsr:@sys/driver-pi@0.0.138/cli';
const TARGET = {
  localSpecifier: '@sys/driver-pi/cli',
  publishedSpecifier: DRIVER_PI_CLI_JSR_SPECIFIER,
  repo: {
    rootDirname: 'sys',
    configFilenames: ['deno.json', 'deno.jsonc'],
    requiredPackages: ['@sys/tools', '@sys/driver-pi'],
    requiredDirs: ['code/sys.tools', 'code/sys.driver/driver-pi'],
  },
} satisfies PassThroughTarget;

export type PiCliDeps = {
  readonly inherit: typeof Process.inherit;
};

const DEFAULT_DEPS: PiCliDeps = Object.freeze({ inherit: Process.inherit });

/** Internal Pi pass-through runner with explicit process effects. */
export async function cliPiWith(
  cwd: t.StringDir | undefined,
  argv: string[] | undefined,
  deps: PiCliDeps = DEFAULT_DEPS,
): Promise<void> {
  cwd = cwd ?? Fs.cwd('process');
  argv = argv ?? [];
  const ctx = await resolvePassThroughContext({ cwd, target: TARGET });
  const permissions = argv[0] === 'dsl' ? '-ER' : '-A';
  const res = await deps.inherit({
    cmd: 'deno',
    cwd,
    env: {
      INIT_CWD: cwd,
      PI_CLI_PROFILES_HELP_TOOL: 'deno run -A jsr:@sys/tools pi',
    },
    args: ['run', permissions, ctx.specifier, ...argv],
  });
  if (!res.success && Is.num(res.code)) Deno.exitCode = res.code;
}
