import { type t, Fs, Is, Path } from './common.ts';
import { FILE, renderStageEntrypoints } from '../m.stage/-tmpl/mod.ts';

type O = Record<string, unknown>;

export async function prepare(
  stage: t.DenoDeploy.Stage.Result,
): Promise<t.DenoDeploy.Pipeline.Prepared> {
  const stagedTargetRel = Path.relative(stage.workspace.dir, stage.target.dir);
  const rendered = renderStageEntrypoints(`./${stagedTargetRel}`);
  const entrypoint = stage.entry;
  const entryPaths = Fs.join(stage.root, FILE.entryPaths);
  const compatEntrypoint = Fs.join(stage.root, FILE.compatEntrypoint);

  await ensureDeployConfig(stage.root);
  await ensureStagedDistIncluded(stage.root, stagedTargetRel);
  await Fs.ensureDir(Fs.join(stage.root, 'src', 'm.server'));
  await Fs.write(compatEntrypoint, rendered.compatEntrypoint);

  return {
    stagedDir: stage.root,
    entrypoint,
    entryPaths,
    appEntrypoint: `./${FILE.compatEntrypoint}`,
    workspaceTarget: `./${stagedTargetRel}`,
    distDir: `./${stagedTargetRel}/dist`,
  };
}

async function ensureDeployConfig(root: string) {
  const path = Fs.join(root, 'deno.json');
  const res = await Fs.readJson<O>(path);
  if (!res.ok || !res.data) throw new Error(`Failed to read staged deno.json: ${path}`);

  const current = res.data;
  const currentDeploy = Is.record(current.deploy) ? current.deploy : {};

  await Fs.writeJson(path, {
    ...current,
    deploy: { ...currentDeploy, entrypoint: './entry.ts', cwd: './' },
  });
}

async function ensureStagedDistIncluded(root: string, targetRel: string) {
  const path = Fs.join(root, '.gitignore');
  const marker = '# generated by driver-deno external prebuilt-dist deploy proof';
  const current = (await Fs.readText(path)).data ?? '';
  if (current.includes(marker)) return;

  const lines = [marker, ...toDistUnignoreRules(targetRel)];
  const prefix = current.length > 0 && !current.endsWith('\n') ? '\n' : '';
  await Fs.write(path, `${current}${prefix}${lines.join('\n')}\n`);
}

function toDistUnignoreRules(targetRel: string): string[] {
  const clean = targetRel.replace(/^\.\//, '').replace(/\/+$/, '');
  const parts = clean.split('/').filter(Boolean);
  const rules: string[] = [];
  let acc = '';

  for (const part of parts) {
    acc = acc.length > 0 ? `${acc}/${part}` : part;
    rules.push(`!${acc}/`);
  }

  const distRel = clean.length > 0 ? `${clean}/dist` : 'dist';
  rules.push(`!${distRel}/`);
  rules.push(`!${distRel}/**`);
  return rules;
}
