# Cell descriptor.

kind: cell
version: 1

services:
  - name: draft:ui
    use: Serve
    from: 'jsr:@sys/tools/serve'
    config: ./-config/@sys.tools.serve/view.yaml
    variants:
      dev:
        use: ViteService
        from: 'jsr:@sys/driver-vite/service'
        config: ./-config/@sys.driver-vite/view.dev.yaml

  - name: draft:files
    use: FilesWebSocketService
    from: 'jsr:@sys/server/files/service'
    config: ./-config/@sys.server.files/shell.yaml
