import { type t, DenoFile, Fs, Is, Process } from './common.ts';

/**
 * AUTO-GENERATED by `code/sys.tools/-scripts/task.prep.ts`.
 * Keeps the published fallback deterministic for `@sys/tools/code`.
 */
const DRIVER_AGENT_PI_CLI_JSR_SPECIFIER = 'jsr:@sys/driver-agent@0.0.26/pi/cli';

/**
 * Main entry.
 *
 * Delegates all argv/cwd handling to the Pi profile launcher.
 */
export const cli: t.CodeToolsLib['cli'] = async (cwd, argv) => {
  cwd = cwd ?? Fs.cwd('terminal');
  argv = argv ?? [];
  const res = await run(cwd, argv);
  if (!res.success && Is.num(res.code)) Deno.exitCode = res.code;
};

async function run(cwd: t.StringDir, argv: string[]) {
  const specifier = await resolveSpecifier(cwd);
  return await Process.inherit({
    cmd: 'deno',
    cwd,
    env: {
      INIT_CWD: cwd,
      PI_CLI_PROFILES_HELP_TOOL: 'deno run -A jsr:@sys/tools agent',
    },
    args: ['run', '-A', specifier, 'Profiles', ...argv],
  });
}

type WorkspaceInfo = {
  readonly exists: boolean;
  readonly dir: t.StringDir;
  readonly file: t.StringPath;
  readonly children: readonly {
    readonly pkg: { readonly name: string };
    readonly path: { readonly dir: t.StringDir };
  }[];
};

async function resolveSpecifier(cwd: t.StringDir): Promise<string> {
  const nearest = await DenoFile.nearest(cwd, (e) => Array.isArray(e.file.workspace));
  if (!nearest?.is.workspace) return DRIVER_AGENT_PI_CLI_JSR_SPECIFIER;

  const ws = await DenoFile.workspace(nearest.path, { walkup: false });
  if (!isSystemRepo(ws)) return DRIVER_AGENT_PI_CLI_JSR_SPECIFIER;
  return '@sys/driver-agent/pi/cli';
}

function isSystemRepo(ws: WorkspaceInfo): boolean {
  if (!ws.exists) return false;
  if (Fs.basename(ws.dir) !== 'sys') return false;
  if (!['deno.json', 'deno.jsonc'].includes(Fs.basename(ws.file))) return false;

  const names = new Set(ws.children.map((child) => child.pkg.name));
  if (!names.has('@sys/tools') || !names.has('@sys/driver-agent')) return false;

  const dirs = new Set(ws.children.map((child) => child.path.dir));
  if (!dirs.has('code/sys.tools') || !dirs.has('code/sys.driver/driver-agent')) return false;

  return true;
}
