// AUTO-GENERATED by `deno task bind:gui:evidence:local`.
// DO NOT EDIT MANUALLY.
// Checked in so `start:gui` can authenticate one frozen local-rehearsal build.
// This is not published release evidence.

export const START_GUI_RELEASE_EVIDENCE = Object.freeze({
  kind: 'release' as const,
  manifestUrl: 'http://localhost:8080/dist.json',
  integrity: 'sha256-520c45fe4c515664c977a8cfce09c1cbbd3c90056d59daaaa069d0a4ce55dbe8',
  expectedPkg: Object.freeze({
    name: '@sys/driver-pi',
    version: '0.0.138',
  }),
});
