// AUTO-GENERATED by `deno task bind:gui:evidence:local`.
// DO NOT EDIT MANUALLY.
// Checked in so `start:gui` can authenticate one frozen local-rehearsal build.
// This is not published release evidence.

export const START_GUI_RELEASE_EVIDENCE = Object.freeze({
  kind: 'release' as const,
  manifestUrl: 'http://localhost:8080/dist.json',
  integrity: 'sha256-bc520eeb1ca7ae56208ba807cb22cac4cb0e4b5c458ba4476b2126fabe36879f',
  expectedPkg: Object.freeze({
    name: '@sys/driver-pi',
    version: '0.0.138',
  }),
});
