// AUTO-GENERATED by `deno task bind:gui:evidence:local`.
// DO NOT EDIT MANUALLY.
// Checked in so `start:gui` can authenticate one frozen local-rehearsal build.
// This is not published release evidence.

export const START_GUI_RELEASE_EVIDENCE = Object.freeze({
  kind: 'release' as const,
  manifestUrl: 'http://localhost:8080/dist.json',
  integrity: 'sha256-762b1f36dbe08714292df4b8529d68eafd2a9ce4601b2d9d8b74032a82fddce5',
  expectedPkg: Object.freeze({
    name: '@sys/driver-pi',
    version: '0.0.138',
  }),
});
