name: ci

on: [push, pull_request]

jobs:
  deno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC/ID token is used for authentication with JSR.
    environment: dev
    env:
      TEST_SAMPLE: ${{ vars.TEST_SAMPLE }}

    steps:
      - uses: actions/checkout@v3

      - name: 'Guard: no bidi/hidden Unicode chars'
        run: .github/-scripts/Task.-prep.check-no-bidi.sh

      - name: 'Install ESM Runtime: Deno 2.x'
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.5.x

      - name: 'Install ES Modules from JSR: https://jsr.io/@sys'
        run: deno task help

      - name: Deno Info
        run: deno info && deno --version

      - name: System Info
        run: deno task help
