import type { t } from './common.ts';

/** The various copy options */
export type CrdtCommand = 'sync' | 'add-doc' | 'remove-doc' | 'list' | 'help';

/**
 * CLI helpers for working with CRDT documents.
 */
export type CrdtToolsLib = {
  /** Run the interactive CLI flow (prompts + spinner). */
  cli(opts?: { dir?: t.StringDir; argv?: string[] }): Promise<void>;
};

/**
 * Command line arguments (argv).
 */
export type CrdtCliArgs = { help: boolean };

/** The structure of the index.json file that stores root information about where the document index is stored. */
export type CrdtIndexJson = {
  readonly kind: 'crdt:index';
  readonly docid: t.StringId;
  readonly created: {
    readonly by: t.StringPkgNameVer;
    readonly at: t.UnixTimestamp;
  };
};

/**
 * The CRDT document that stores index information
 * generated by the CLI tool itself.
 */
export type CrdtIndexDocRef = t.Crdt.Ref<t.CrdtIndexDoc>;
export type CrdtIndexDoc = { watching?: CrdtIndexItem[] };
export type CrdtIndexItem = {
  docid: t.StringId;
  addedAt: t.UnixTimestamp;
  name?: string;
};
