import { cli as tmplCli } from '@sys/tmpl';

import { type t, Fs, Path, Str } from './common.ts';
import { Fmt } from '../../u.fmt.ts';

export async function createDeployableRepoPkg(): Promise<{
  readonly root: t.StringDir;
  readonly pkgDir: t.StringDir;
}> {
  const root = await createPublishedRepoFixture();
  const pkgDir = Fs.join(root, 'code', 'projects', 'foo');

  await tmplCli(root, {
    _: ['pkg'],
    tmpl: 'pkg',
    interactive: false,
    dryRun: false,
    force: true,
    bundle: false,
    dir: 'code/projects/foo',
    pkgName: '@tmp/foo',
    help: false,
    'no-interactive': true,
  });

  return { root, pkgDir };
}

export async function snapshotPackageDenoJson() {
  const path = Fs.Path.fromFileUrl(new URL('../../../../deno.json', import.meta.url));
  const text = (await Fs.readText(path)).data ?? '';
  return { path, text } as const;
}

export async function restorePackageDenoJsonIfPolluted(snapshot: { readonly path: string; readonly text: string }) {
  const current = (await Fs.readText(snapshot.path)).data ?? '';
  if (current === snapshot.text) return;
  await Fs.write(snapshot.path, snapshot.text);
}

async function createPublishedRepoFixture(): Promise<t.StringDir> {
  const root = (await Fs.makeTempDir({ prefix: 'tmpl.deploy.repo.' })).absolute as t.StringDir;
  await quietly(() =>
    tmplCli(root, {
      _: ['repo'],
      tmpl: 'repo',
      interactive: false,
      dryRun: false,
      force: true,
      bundle: false,
      dir: '.',
      help: false,
      'no-interactive': true,
    }),
  );
  return root;
}

export async function prepareStageForExistingApp(stage: t.DenoDeploy.Stage.Result) {
  const stagedTargetRel = Path.relative(stage.workspace.dir, stage.target.dir);
  const entrypoint = stage.entry;
  const entryPaths = Fs.join(stage.root, 'entry.paths.ts');
  const compatEntrypoint = Fs.join(stage.root, 'src/m.server/main.ts');
  await ensureDeployConfig(stage.root);
  await ensureStagedDistIncluded(stage.root, stagedTargetRel);
  await Fs.ensureDir(Fs.join(stage.root, 'src', 'm.server'));

  await Fs.write(
    compatEntrypoint,
    Str.dedent(`
      export { default } from '../../entry.ts';
      export * from '../../entry.ts';
    `),
  );

  return {
    stagedDir: stage.root,
    entrypoint,
    entryPaths,
    appEntrypoint: './src/m.server/main.ts',
    workspaceTarget: `./${stagedTargetRel}`,
    distDir: `./${stagedTargetRel}/dist`,
  } as const;
}

export function printDeployEntrypointInfo(args: {
  readonly stagedDir: string;
  readonly entrypoint: string;
  readonly entryPaths: string;
  readonly appEntrypoint: string;
  readonly workspaceTarget: string;
  readonly distDir: string;
}) {
  for (const line of Fmt.info({
    title: 'Staged Deploy Entrypoint',
    rows: [
      { label: 'staged dir', value: args.stagedDir, color: 'white' },
      { label: 'entry', value: args.entrypoint, color: 'white' },
      { label: 'entry paths', value: args.entryPaths, color: 'white' },
      { label: 'app config', value: args.appEntrypoint, color: 'white' },
      { label: 'workspace', value: args.workspaceTarget, color: 'white' },
      { label: 'dist', value: args.distDir, color: 'white' },
    ],
  })) {
    console.info(line);
  }
}

async function quietly<T>(run: () => Promise<T>): Promise<T> {
  const info = console.info;
  const log = console.log;
  const warn = console.warn;
  try {
    console.info = () => undefined;
    console.log = () => undefined;
    console.warn = () => undefined;
    return await run();
  } finally {
    console.info = info;
    console.log = log;
    console.warn = warn;
  }
}

async function ensureDeployConfig(root: string) {
  const path = Fs.join(root, 'deno.json');
  const res = await Fs.readJson<Record<string, unknown>>(path);
  if (!res.ok || !res.data) throw new Error(`Failed to read staged deno.json: ${path}`);

  const current = res.data;
  const currentDeploy =
    typeof current.deploy === 'object' && current.deploy !== null ? (current.deploy as Record<string, unknown>) : {};

  await Fs.writeJson(path, {
    ...current,
    deploy: {
      ...currentDeploy,
      entrypoint: './entry.ts',
      cwd: './',
    },
  });
}

async function ensureStagedDistIncluded(root: string, targetRel: string) {
  const path = Fs.join(root, '.gitignore');
  const marker = '# generated by driver-deno external prebuilt-dist deploy proof';
  const current = (await Fs.readText(path)).data ?? '';
  if (current.includes(marker)) return;

  const lines = [marker, ...toDistUnignoreRules(targetRel)];
  const prefix = current.length > 0 && !current.endsWith('\n') ? '\n' : '';
  await Fs.write(path, `${current}${prefix}${lines.join('\n')}\n`);
}

function toDistUnignoreRules(targetRel: string): string[] {
  const clean = targetRel.replace(/^\.\//, '').replace(/\/+$/, '');
  const parts = clean.split('/').filter(Boolean);
  const rules: string[] = [];
  let acc = '';

  for (const part of parts) {
    acc = acc.length > 0 ? `${acc}/${part}` : part;
    rules.push(`!${acc}/`);
  }

  const distRel = clean.length > 0 ? `${clean}/dist` : 'dist';
  rules.push(`!${distRel}/`);
  rules.push(`!${distRel}/**`);
  return rules;
}
