name: build
on:
  push:
    branches:
      - main
      - phil-work
  pull_request:
    branches:
      - main

jobs:
  deno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: dev
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "build: @sys/ui-react-devharness"
            path: code/sys.ui/ui-react-devharness
          - name: "build: @sys/ui-react-components"
            path: code/sys.ui/ui-react-components
          - name: "build: @sys/ui-factory"
            path: code/sys.ui/ui-factory
          - name: "build: @sys/driver-automerge"
            path: code/sys.driver/driver-automerge
          - name: "build: @sys/driver-monaco"
            path: code/sys.driver/driver-monaco
          - name: "build: @sys/driver-prosemirror"
            path: code/sys.driver/driver-prosemirror
          - name: "build: @sys/driver-stripe"
            path: code/sys.driver/driver-stripe
          - name: "build: @tdb/slc-std"
            path: deploy/@tdb.slc.std
          - name: "build: @tdb/edu-slug"
            path: deploy/@tdb.edu.slug
          - name: "build: @tdb/slc"
            path: deploy/@tdb.slc
          - name: "build: @tdb/slc-fs"
            path: deploy/@tdb.slc.fs
          - name: "build: @sys/dev"
            path: code/sys.dev
          - name: "build: @sys/crdt"
            path: code/sys/crdt
    steps:
      - uses: actions/checkout@v3
      - name: 'Install ESM Runtime: Deno 2.x'
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.5.x
      - name: 'Install ES Modules from JSR: https://jsr.io/@sys'
        run: deno task help
      - name: Deno Info
        run: deno info && deno --version
      - name: System Info
        run: deno task help
      - name: build module → "${{ matrix.name }}"
        run: |
          cd ${{ matrix.path }}
          deno task build
