# https://docs.deno.com/deploy/manual/ci_github
# https://jsr.io/docs/publishing-packages#publishing-from-github-actions

name: jsr

on:
  push:
    branches:
      - main
      - phil-work

jobs:
  deno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC/ID token is used for authentication with JSR.
    environment: dev
    env:
      TEST_SAMPLE: ${{ vars.TEST_SAMPLE }}
      DENO_SUBHOSTING_ACCESS_TOKEN: ${{ secrets.DENO_SUBHOSTING_ACCESS_TOKEN }}
      DENO_SUBHOSTING_DEPLOY_ORG_ID: ${{ vars.DENO_SUBHOSTING_DEPLOY_ORG_ID }}
      PRIVY_APP_ID: ${{ vars.PRIVY_APP_ID }}
      PRIVY_APP_SECRET: ${{ secrets.PRIVY_APP_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2

      - name: publish module → "@sys/types"
        run: |
          cd code/sys/types
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/std"
        run: |
          cd code/sys/std
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/color"
        run: |
          cd code/sys/color
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/cli"
        run: |
          cd code/sys/cli
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/crypto"
        run: |
          cd code/sys/crypto
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/fs"
        run: |
          cd code/sys/fs
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/process"
        run: |
          cd code/sys/process
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/http"
        run: |
          cd code/sys/http
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/text"
        run: |
          cd code/sys/text
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/tmpl"
        run: |
          cd code/sys/tmpl
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/cmd"
        run: |
          cd code/sys/cmd
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/jsr"
        run: |
          cd code/sys/jsr
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/main"
        run: |
          cd code/sys/main
          deno task test --parallel --trace-leaks
          deno publish --allow-dirty

      - name: publish module → "@sys/testing"
        run: |
          cd code/sys/testing
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/ui-css"
        run: |
          cd code/sys.ui/ui-css
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/ui-dom"
        run: |
          cd code/sys.ui/ui-dom
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/ui-react"
        run: |
          cd code/sys.ui/ui-react
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/ui-react-devharness"
        run: |
          cd code/sys.ui/ui-react-devharness
          deno task test --parallel
          deno publish --allow-dirty

      #  🐷
      # - name: publish module → "@sys/driver-automerge"
      #   run: |
      #     cd code/sys.driver/driver-automerge
      #     deno task test --parallel
      #     deno publish --allow-dirty

      - name: publish module → "@sys/driver-deno"
        run: |
          cd code/sys.driver/driver-deno
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/driver-immer"
        run: |
          cd code/sys.driver/driver-immer
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/tmp"
        run: |
          cd code/sys.tmp
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/driver-vite"
        run: |
          cd code/sys.driver/driver-vite
          deno task test --parallel --trace-leaks
          deno publish --allow-dirty

      - name: publish module → "@sys/driver-vitepress"
        run: |
          cd code/sys.driver/driver-vitepress
          deno task test --parallel --trace-leaks
          deno publish --allow-dirty

      - name: publish module → "@sys/driver-obsidian"
        run: |
          cd code/sys.driver/driver-obsidian
          deno task test --parallel
          deno publish --allow-dirty

      - name: publish module → "@sys/driver-ollama"
        run: |
          cd code/sys.driver/driver-ollama
          deno task test --parallel --trace-leaks
          deno publish --allow-dirty

      - name: publish module → "@sys/driver-orbiter"
        run: |
          cd code/sys.driver/driver-orbiter
          deno task test --parallel --trace-leaks
          deno publish --allow-dirty

      - name: publish module → "@sys/driver-quilibrium"
        run: |
          cd code/sys.driver/driver-quilibrium
          deno task test --parallel
          deno publish --allow-dirty
