# https://docs.deno.com/deploy/manual/ci_github
# https://jsr.io/docs/publishing-packages#publishing-from-github-actions

name: jsr

on:
  push:
    branches:
      - main
      - phil-work

jobs:
  deno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    environment: dev
    env:
      TEST_SAMPLE: ${{ vars.TEST_SAMPLE }}
      DENO_SUBHOSTING_ACCESS_TOKEN: ${{ secrets.DENO_SUBHOSTING_ACCESS_TOKEN }}
      DENO_SUBHOSTING_DEPLOY_ORG_ID: ${{ vars.DENO_SUBHOSTING_DEPLOY_ORG_ID }}
      PRIVY_APP_ID: ${{ vars.PRIVY_APP_ID }}
      PRIVY_APP_SECRET: ${{ secrets.PRIVY_APP_SECRET }}

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v2

      - name: publish module → "@sys/types"
        run: |
          cd code/sys/types
          deno task test
          deno publish

      - name: publish module → "@sys/std"
        run: |
          cd code/sys/std
          deno task test
          deno publish

      - name: publish module → "@sys/std-s"
        run: |
          cd code/sys/std-s
          deno task test
          deno publish

      - name: publish module → "@sys/cmd"
        run: |
          cd code/sys/cmd
          deno task test
          deno publish

      - name: publish module → "@sys/tmp"
        run: |
          cd code/sys.tmp
          deno task test
          deno publish

      - name: publish module → "@sys/ui-react"
        run: |
          cd code/sys.ui/ui-react
          deno task test
          deno publish --dry-run --allow-slow-types

      # - name: publish module → "@sys/driver-automerge"
      #   run: |
      #     cd code/sys.driver/driver-automerge
      #     deno task test
      #     deno publish

      - name: publish module → "@sys/driver-deno"
        run: |
          cd code/sys.driver/driver-deno
          deno task test
          deno publish

      - name: publish module → "@sys/driver-immer"
        run: |
          cd code/sys.driver/driver-immer
          deno task test
          deno publish

      - name: publish module → "@sys/driver-vite"
        run: |
          cd code/sys.driver/driver-vite
          deno task test
          deno publish
